// SPDX-License-Identifier: GPL-2.0
/*
 * arch/wasm/kernel/kallsyms.c: empty kallsyms tables.
 *
 * The kernel symbol table is normally generated by scripts/kallsyms as
 * part of the standard vmlinux link.  The wasm build links the kernel
 * with zig cc directly and cannot run that pass, so these zero-length
 * tables make the generic kallsyms code a harmless no-op.
 */

#include <linux/types.h>

const unsigned long kallsyms_addresses[] = { 0 };
const int kallsyms_offsets[] = { 0 };
const u8 kallsyms_names[] = { 0 };
const unsigned int kallsyms_num_syms = 0;
const unsigned long kallsyms_relative_base = 0;
const char kallsyms_token_table[] = { 0 };
const u16 kallsyms_token_index[] = { 0 };
const unsigned int kallsyms_markers[] = { 0 };
const u8 kallsyms_seqs_of_names[] = { 0 };
