# SPDX-License-Identifier: GPL-2.0
obj-y = setup.o process.o irq.o time.o console.o syscall.o traps.o mem.o \
	init.o markers.o jiffies.o kallsyms.o sched.o shell.o
obj-$(CONFIG_WASM_NET) += netdev.o

